### ISSUE TITLE
下载的GTOT数据集里没有challenge tag

### ISSUE THREAD

**Issue by carry-all-coder** [yangmengmeng1997/APFNet#1]
您好，这是一篇非常棒的工作！但我在复现的时候遇到一点小问题，我下载了GTOT数据集，但里面的目录里找不到所谓的challenge tag，下载数据集如下所示：
![2022-05-12 20-05-44屏幕截图](https://user-images.githubusercontent.com/52854971/168071256-0119737e-d9e6-4e8b-8e85-a25f3937b3ed.png)
这是我的数据集设置：
![2022-05-12 20-09-33屏幕截图](https://user-images.githubusercontent.com/52854971/168071539-1c64be03-1b29-46ee-bab1-7aa880d8b362.png)

请问这些challenge tag是需要预处理才能获得吗？

**Comment by yangmengmeng1997** [comment]
你好，已经更新数据，现在有挑战标签了，这些标签是人工标注的，之前是我们的疏忽导致上传了没有挑战标签的数据

**Comment by carry-all-coder** [comment]
> 你好，已经更新数据，现在有挑战标签了，这些标签是人工标注的，之前是我们的疏忽导致上传了没有挑战标签的数据
您好！非常感谢您耐心及时的回复！数据集确实已经更新，但现在因为单个数据集内文件夹数量过多，已经超出了超级会员的转存权限，而且分开一点点下载数量也十分感人，不知是否有压缩后的版本呢？感谢！

**Comment by yangmengmeng1997** [comment]
你好，我这边本地也没有存储这个数据集，我这边也只能一个一个下载然后在本地压缩后重新上传

**Comment by PengFG** [comment]
您好！我非常喜欢您的工作，然而我也同样遇到了数据集的问题，带有init.txt标注文件的RGBT234数据集无法找到，给定的百度云链接目前已经无法下载，请问能否发布新的下载链接？
