### ISSUE TITLE
Pretrained Model Link

### ISSUE THREAD

**Issue by 0xVortex** [yangmengmeng1997/APFNet#3]
Link of pretrained model is broken or I can't reach it because of Baidu's policies. Can you renew it or upload to another cloud platform except Baidu?

**Comment by yangmengmeng1997** [comment]
The new link is [here](https://drive.google.com/drive/folders/1T49HqgBWKA2kWlNP5roGwOZWJK_-icnn?usp=sharing)

**Comment by 0xVortex** [comment]
Thank you very much.
