### ISSUE TITLE
Challenge Tag

### ISSUE THREAD

**Issue by 0xVortex** [yangmengmeng1997/APFNet#6]
I'm trying to train APFNEt but I have a problem with creating .pkl files for different challenge types. There is no .tag file (for example fast_motion.tag) in RGBT-234 or GTOT datasets. Have you created these tag files on your own? Do you have end can you share them with me? If you don't have them, can you tell me how to create them? Thank you very much.

` if challenge_type == 'FM':
        challenge_inf = 'fast_motion.tag'
    elif challenge_type == 'OCC':
        challenge_inf = 'occlusion.tag'
    elif challenge_type == 'SC':
        challenge_inf = 'size_change.tag'
    elif challenge_type == 'ILL':
        challenge_inf = 'illum_change.tag'
    elif challenge_type == 'TC':
        challenge_inf = 'thermal_crossover.tag'
    elif challenge_type == 'ALL':
        data[seqname] = {'images_v':img_list_v, 'images_i':img_list_i, 'gt':gt}`

**Comment by yangmengmeng1997** [comment]
you can find the tags in&nbsp;https://github.com/mmic-lcl/Datasets-and-benchmark-code
Here, you can find .tag files in 'RGBT234' and 'GTOT' Baidu network disk.such as this.
Good Luck!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangmengmeng1997/APFNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月1日(星期二) 凌晨3:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yangmengmeng1997/APFNet] Challenge Tag (Issue #6)





 
I'm trying to train APFNEt but I have a problem with creating .pkl files for different challenge types. There is no .tag file (for example fast_motion.tag) in RGBT-234 or GTOT datasets. Have you created these tag files on your own? Do you have end can you share them with me? If you don't have them, can you tell me how to create them? Thank you very much.
 
 if challenge_type == 'FM': challenge_inf = 'fast_motion.tag' elif challenge_type == 'OCC': challenge_inf = 'occlusion.tag' elif challenge_type == 'SC': challenge_inf = 'size_change.tag' elif challenge_type == 'ILL': challenge_inf = 'illum_change.tag' elif challenge_type == 'TC': challenge_inf = 'thermal_crossover.tag' elif challenge_type == 'ALL': data[seqname] = {'images_v':img_list_v, 'images_i':img_list_i, 'gt':gt}

**Comment by 0xVortex** [comment]
Ok, I got it! Thank you for your help.
