### ISSUE TITLE
about CMPP results

### ISSUE THREAD

**Issue by 972821054** [yangmengmeng1997/APFNet#7]
hello!
Thank you very much for your contribution in the field of RGBT object tracking. I reproduced your code and got excellent results. I have a question, how did you obtain the results of CMPP and CAT during the evaluation, I did not find relevant data or codes. I would be very grateful if you could help me!

**Comment by yangmengmeng1997** [comment]
**https://github.com/mmic-lcl/Datasets-and-benchmark-code** 
you can find all results in tracking results of this resposity.
